version: "2"

services:
    api:
        build:
            context: ./api
        volumes:
            - ./api:/app/site
            - ./data/metadata:/app/site/metadata
            - ./ui/src/web-api:/app/site/web-api
    ui:
        build:
            context: ./ui
        volumes:
            - "./ui:/app"
            - "./data/graphql:/app/src/data/graphql"
            - "./data/types:/app/src/data/types"
            - "/app/node_modules"
        ports:
            - "4200:4200"
